// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qGEAMMnTfNSc8-Z4XnF9c3nTEtLXH3Y',
    appId: '1:140096059742:web:1b142e10323157e9fdb7cf',
    messagingSenderId: '140096059742',
    projectId: 'kgbox-83b4d',
    authDomain: 'kgbox-83b4d.firebaseapp.com',
    storageBucket: 'kgbox-83b4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl12Ftnp6P6X7mDw2bcMQyw53_dvpMmZc',
    appId: '1:140096059742:android:a0d00b51c32279ecfdb7cf',
    messagingSenderId: '140096059742',
    projectId: 'kgbox-83b4d',
    storageBucket: 'kgbox-83b4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Wk-b9c61SJAha0muPr0DWk6y8WNB99U',
    appId: '1:140096059742:ios:54e6b003ad42c85ffdb7cf',
    messagingSenderId: '140096059742',
    projectId: 'kgbox-83b4d',
    storageBucket: 'kgbox-83b4d.firebasestorage.app',
    iosBundleId: 'com.example.kgbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Wk-b9c61SJAha0muPr0DWk6y8WNB99U',
    appId: '1:140096059742:ios:54e6b003ad42c85ffdb7cf',
    messagingSenderId: '140096059742',
    projectId: 'kgbox-83b4d',
    storageBucket: 'kgbox-83b4d.firebasestorage.app',
    iosBundleId: 'com.example.kgbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5qGEAMMnTfNSc8-Z4XnF9c3nTEtLXH3Y',
    appId: '1:140096059742:web:3a4276d3b26b42bbfdb7cf',
    messagingSenderId: '140096059742',
    projectId: 'kgbox-83b4d',
    authDomain: 'kgbox-83b4d.firebaseapp.com',
    storageBucket: 'kgbox-83b4d.firebasestorage.app',
  );
}
