// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuAFg6TcPSEB3bL6osj1ZmpblqHDMIz5M',
    appId: '1:868462308934:web:81d79ab254a6df6a70e447',
    messagingSenderId: '868462308934',
    projectId: 'kgbox-f93ae',
    authDomain: 'kgbox-f93ae.firebaseapp.com',
    storageBucket: 'kgbox-f93ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUwl2g_ejgPy_3_bmvpvCOwlEne72Zq4',
    appId: '1:868462308934:android:053559afda3b843b70e447',
    messagingSenderId: '868462308934',
    projectId: 'kgbox-f93ae',
    storageBucket: 'kgbox-f93ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAk_grNZGbAvVUiYj9fAJGfS6vFgMscE',
    appId: '1:868462308934:ios:8ba6a257108b1d3170e447',
    messagingSenderId: '868462308934',
    projectId: 'kgbox-f93ae',
    storageBucket: 'kgbox-f93ae.firebasestorage.app',
    iosClientId: '868462308934-vhsfo4v111gitdb22ccsak658hml2941.apps.googleusercontent.com',
    iosBundleId: 'com.example.kgDns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAk_grNZGbAvVUiYj9fAJGfS6vFgMscE',
    appId: '1:868462308934:ios:8ba6a257108b1d3170e447',
    messagingSenderId: '868462308934',
    projectId: 'kgbox-f93ae',
    storageBucket: 'kgbox-f93ae.firebasestorage.app',
    iosClientId: '868462308934-vhsfo4v111gitdb22ccsak658hml2941.apps.googleusercontent.com',
    iosBundleId: 'com.example.kgDns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuAFg6TcPSEB3bL6osj1ZmpblqHDMIz5M',
    appId: '1:868462308934:web:aa14261a4975006570e447',
    messagingSenderId: '868462308934',
    projectId: 'kgbox-f93ae',
    authDomain: 'kgbox-f93ae.firebaseapp.com',
    storageBucket: 'kgbox-f93ae.firebasestorage.app',
  );
}
